# Setting Spring context path & port
server.port=8082

# Datasource settings
spring.data.mongodb.uri=${DB_URL}
spring.main.allow-bean-definition-overriding=true

# Kafka Notifier Service
kafka.notifier.base-url=${KAFKA_NOTIFIER_URL:http://localhost:8085/spring-kafka-notifier}