# Import external configuration
spring:
  config:
    import: 
      - classpath:kafka.properties
  application:
    name: ${action.manager.service.name}
  profiles:
    active: ${spring.profiles.active}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

# Server configuration
server:
  servlet:
    context-path: /${action.manager.service.name}
  error:
    include-message: always
    include-binding-errors: always

# SpringDoc configuration
springdoc:
  swagger-ui:
    enabled: ${springdoc.swagger-ui.enabled}
    path: /swagger-ui.html
  api-docs:
    enabled: ${springdoc.api-docs.enabled}
  packages-to-scan: com.hoatv.action.manager

# Management configuration
management:
  metrics:
    tags:
      application: action-manager
  endpoints:
    web:
      exposure:
        include:
          - health
          - loggers
          - info
          - prometheus
